spring:
  application:
    name: Enotes-API-Service
  profiles:
    active: dev

---
# Dev Config
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/enotes_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: MySQL@07
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    username: nymansa.gupta@gmail.com
    password: mqsp wmhe lgcj qoiw
    port: 587
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true

springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    path: /enotes-doc
  api-docs:
    path: /enotes-api-doc

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: beans, loggers

file:
  upload:
    path: notes/

server:
  port: 9090

---
# Test Config
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/enotes_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: MySQL@07
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql : true
        format_sql: true
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    username: nymansa.gupta@gmail.com
    password: mqsp wmhe lgcj qoiw
    port: 587
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true

springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    path: /enotes-doc
  api-docs:
    path: /enotes-api-doc

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: beans, loggers

file:
  upload:
    path: notes/

server:
  port: 9091

---
# Prod Config
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/enotes_prod
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: MySQL@07
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    username: nymansa.gupta@gmail.com
    password: mqsp wmhe lgcj qoiw
    port: 587
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true

springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    path: /enotes-doc
  api-docs:
    path: /enotes-api-doc

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: beans, loggers

file:
  upload:
    path: notes/

server:
  port: 9092

---
# Uat Config
spring:
  config:
    activate:
      on-profile: uat
  datasource:
    url: jdbc:mysql://localhost:3306/enotes_uat
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: MySQL@07
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    username: nymansa.gupta@gmail.com
    password: mqsp wmhe lgcj qoiw
    port: 587
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true

springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    path: /enotes-doc
  api-docs:
    path: /enotes-api-doc

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: beans, loggers

file:
  upload:
    path: notes/

server:
  port: 9093

